Networking (homework 7)
alex-zdns/AndroidAcademy pull request #6
Opened 2021-01-08 19:08 UTC by alex-zdns

2021-01-10 11:23 UTC, an-yurii requested changes

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/network/MovieService.kt
> +interface MovieService {
Service в Андроид - один из основных компонентов приложения https://developer.android.com/guide/components/services
Данный интерфейс принято называть api. `MovieApi`

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/network/NetworkModule.kt
> +    val theMovieDBApiService: MovieService = retrofit.create()
В приложении может быть несколько api интерфейсов. Нужно придерживаться принципа разделения отвественности.
Общим разделяемым ресурсом должен быть объект Retrofit. Api будет сконструирован там, где он нужен.

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/network/NetworkModule.kt
> +    private val json = Json {
Тоже стоит добавить ленивую инициализацию.

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/network/dto/CastDTO.kt
> +data class CastDTO(
Аббревиатуры принято писать с заглавной буквы
`CastDTO` -> `CastDto`

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/network/dto/CreditsResponse.kt
> +data class CreditsResponse (
Response - больше чем структура, которая возвращается ретрофитом. В данном случае - это просто dto.
`CreditsDto`

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/network/dto/GenreDTO.kt
> +data class GenreDTO (
`GenreDTO` -> `GenreDto`

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/network/dto/GenresResponse.kt
> +data class GenresResponse(
`GenresResponse` -> `GenresDto`

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/network/dto/MovieDTO.kt
> +data class MovieDTO (
`MovieDTO` -> `MovieDto`

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/movieDetails/MovieDetailsViewModel.kt
> +        NetworkModule.theMovieDBApiService.getCasts(movieId).cast
Необходимо соблюдать принцип инверсии зависимостей и передавать api параметром конструктура. В противном случае получается запутанный и трудносопровождаемый код.
https://t.me/aa_fundamentals_0/668

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/moviesList/MoviesListViewModel.kt
> +            .map { NetworkModule.theMovieDBApiService.getMovieDetailsAsync(movieId = it) }
api интерфейс нужно передавать параметром конструктора. https://t.me/aa_fundamentals_0/668

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/moviesList/MoviesListViewModel.kt
> +    private fun parseMovie(moviesDTO: List<MovieDTO>): List<Movie> =
Это не парсер, а маппер.

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/moviesList/MoviesListViewModel.kt
> +            .map { NetworkModule.theMovieDBApiService.getMovieDetailsAsync(movieId = it) }
Очень плохо. Ты бомбардируешь запросами сервер. Нужно стараться делать как можно меньше запросов. В противном случае нагружается сервер и замедляется работа приложения. Вся необходимая информация для отображения списка возвращается методом getPopularMovie

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/moviesList/MoviesListViewModel.kt
> +                genres = movieDTO.genres.map { genreDTO -> Genre(genreDTO.id, genreDTO.name) }
Нужно стараться делать как можно проще. На данном этапе в приложении нет никакой функциональности связанной с жанрами, кроме отображения списком. В доменной модели можно обойтись строкой или списком строк.

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/moviesList/MoviesListFragment.kt
> +        recycler = null
Нет необходимости занулять переменные, которые живут вместе с активити/фрагментом. Они будут уничтожены, когда на них не будет ссылок. В том числе, после того как переменной будет присвоено новое значение.

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/movieDetails/MovieDetailsViewModelFactory.kt
> +class MovieDetailsViewModelFactory(private val movieId: Long): ViewModelProvider.Factory {
Не вижу необходимости передавать идентификатор параметром конструктора в фабрику. Достаточно будет передать параметром метода во вью модель.

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/movieDetails/MovieDetailsFragment.kt
> +            view?.run {
Правильнее использовать идиому https://kotlinlang.org/docs/idioms.html#execute-if-not-null
```
view?.let {
    it.findViewById<TextView>(R.id.mdf_tv_cast_heading).isVisible = true
    ...
}
```

2021-01-10 11:23 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/network/dto/MoviesResponse.kt
> +    val movies: List<MovieShortDTO>,
Излишняя нагрузка на сервер, вся необходимая информация возвращается запросом.

2021-01-10 14:27 UTC, alex-zdns commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/moviesList/MoviesListViewModel.kt
> +            .map { NetworkModule.theMovieDBApiService.getMovieDetailsAsync(movieId = it) }
Я хотел соответствовать макету из фигмы. Метод getPopularMovie не отдает runtime фильмов. Ради получения этого значения и делались 20 новых запросов. 
Убрал из карточки фильма информацию о длительности.

2021-01-12 15:31 UTC, an-yurii approved these changes
Отлично)

2021-01-12 15:31 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/movieDetails/MovieDetailsViewModelFactory.kt
> +        MovieDetailsViewModel::class.java -> MovieDetailsViewModel(NetworkModule.retrofit.create(MovieApi::class.java))
Есть еще один вариант метода create(). Компилятор Котлин умеет приводить к нужному типу.
```suggestion
        MovieDetailsViewModel::class.java -> MovieDetailsViewModel(NetworkModule.retrofit.create())
```

2021-01-12 15:31 UTC, an-yurii commented on app/src/main/java/ru/alexzdns/fundamentals/homework/ui/moviesList/MoviesListViewModelFactory.kt
> +        MoviesListViewModel::class.java -> MoviesListViewModel(NetworkModule.retrofit.create(MovieApi::class.java))
```suggestion
        MoviesListViewModel::class.java -> MoviesListViewModel(NetworkModule.retrofit.create())
```

2021-01-14 17:34 UTC, merged